version: 2
jobs:
  review:
    working_directory: ~/build
    
    docker:
      - image: hashicorp/terraform:latest
          
    steps:
      - checkout
      - run:
          name: terraform init
          command: terraform init
          working_directory: ~/build/deploy
      - run:
          name: circleci sucks
          command: |
            echo 'export TF_PLAN="terraform plan -input=false -out=terraform.plan -var 'aws_access_key=$AWS_ACCESS_KEY_ID' -var 'aws_secret_key=$AWS_SECRET_KEY'"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: terraform plan
          command: |
            sh -c ${TF_PLAN}
          working_directory: ~/build/deploy
              
      - persist_to_workspace:
          root: /home/build/
          paths:
            - ./

  apply:
    working_directory: ~/build/deploy

    docker:
      - image: hashicorp/terraform:latest

    steps:
      - attach_workspace:
          at: /home/circleci/terraform
      - run:
          name: apply terraform plan
          command: terraform apply -input=false terraform.plan
          working_directory: ~/build/deploy
          
workflows:
  version: 2
  review_apply:
    jobs:
    - review
    - hold:
        type: approval
        requires:
        - review
    - apply:
        requires:
        - hold