version: 2
jobs:
  review:
    working_directory: ~/build
    
    docker:
      - image: hashicorp/terraform:latest
          
    steps:
      - checkout
      - run:
          name: terraform init
          command: terraform init
          working_directory: ~/build/deploy/scripts
          
      - run:
          name: terraform plan
          command: sh ./terraform-plan.sh
          working_directory: ~/build/deploy/scripts
              
      - persist_to_workspace:
          root: /root/build
          paths:
            - ./

  apply:
    working_directory: /home/circleci/terraform/deploy/scripts

    docker:
      - image: hashicorp/terraform:latest

    steps:
      - attach_workspace:
          at: /home/circleci/terraform
      - run:
          name: apply terraform
          command: sh ./terraform-apply.sh
          
workflows:
  version: 2
  review_apply:
    jobs:
    - review
    - hold:
        type: approval
        requires:
          - review
    - apply:
        requires:
        - hold