version: 2
jobs:
  review:
    working_directory: ~/build
    
    docker:
      - image: hashicorp/terraform:latest
        
    steps:
      - checkout
      - run:
          name: terraform plan
          command: terraform plan -input=false -out=terraform.plan
      
      - persist_to_workspace:
          root: /home/circleci/terraform
          paths:
            - ./

  apply:
    working_directory: ~/deploy/

    docker:
      - image: hashicorp/terraform:latest

    steps:
      - attach_workspace:
          at: /home/circleci/terraform
      - run:
          name: apply terraform plan
          command: terraform apply -input=false terraform.plan
          
workflows:
  version: 2
  review_apply:
    jobs:
    - review
    - hold:
        type: approval
        requires:
        - review
    - apply:
        requires:
        - hold